[project]
name = "ai-interview-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "accelerate==0.34.2",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "beautifulsoup4>=4.15.0",
    "bitsandbytes>=0.49.2",
    "chromadb>=1.5.9",
    "datasets>=5.0.0",
    "dotenv>=0.9.9",
    "edge-tts>=7.2.8",
    "en-core-web-trf",
    "fastapi>=0.137.1",
    "faster-whisper==1.2.1",
    "groq>=1.4.0",
    "gtts>=2.5.4",
    "hdbscan>=0.8.44",
    "huggingface-hub>=0.34.0",
    "ipykernel>=7.3.0",
    "jose>=1.0.0",
    "jwt>=1.4.0",
    "langgraph>=1.2.6",
    "langgraph-checkpoint-postgres>=3.1.0",
    "livekit>=0.18.3",
    "livekit-agents>=1.6.1",
    "livekit-plugins-cartesia>=1.6.1",
    "livekit-plugins-deepgram>=1.6.1",
    "livekit-plugins-groq>=1.6.1",
    "livekit-plugins-openai>=1.6.1",
    "livekit-plugins-silero>=1.6.1",
    "neo4j>=6.2.0",
    "numpy>=1.26.4",
    "openai-whisper>=20250625",
    "pandas>=3.0.3",
    "peft>=0.19.1",
    "pgvector>=0.4.2",
    "psycopg-pool>=3.3.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.14.1",
    "pydantic[email]>=2.13.4",
    "pydub>=0.25.1",
    "pyjwt>=2.13.0",
    "pypdf>=6.14.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "sentence-transformers>=5.6.0",
    "spacy>=3.8.14",
    "spacy-transformers>=1.4.0",
    "sqlalchemy>=2.0.0",
    "tavily>=1.1.0",
    "tavily-python>=0.7.26",
    "torch>=2.12.0",
    "torchaudio>=2.11.0",
    "transformers>=4.51.3,<5.0.0",
    "trl==0.15.1",
    "umap-learn>=0.5.12",
    "unsloth>=2025.7.2",
    "unsloth-zoo>=2025.7.4",
    "uvicorn>=0.49.0",
    "wandb>=0.26.1",
]

[tool.uv.sources]
en-core-web-trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl" }
